```{python}
#| include: false
#| warning: false
issues, prs = gha.get_all(data, lang)

issues_open = gha.get_open(issues)
issues_open_new = issues_open[issues_open.author_association == "NONE"]
issues_open_no_replies = issues_open[issues_open.comments == 0]

prs_open = gha.get_open(prs)
prs_open_new = prs_open[prs_open.author_association == "FIRST_TIME_CONTRIBUTOR"]
prs_open_no_replies = prs_open[prs_open.comments == 0]

issues_sum_new, issues_sum_others = gha.get_summary(issues)
x_issues_others = issues_sum_others["created_at"]
y_issues_others = issues_sum_others["sum"]
y_issues_new = issues_sum_new["sum"]
prs_sum_new, prs_sum_others = gha.get_summary(prs)
x_prs_others = prs_sum_others["created_at"]
y_prs_others = prs_sum_others["sum"]
y_prs_new = prs_sum_new["sum"]

data_ml = ml.get_all(lang)

content = gha.get_issues_content(data, lang)
summary_github = llm_github.summarise_github_issues(content, lang)
```

```{r}
#| include: false
#| warning: false
vector_tags = c("apache-arrow", py$lang)
if(py$lang == "Python"){
    append(vector_tags, c("pyarrow", "python"))
}

questions_content <- get_questions(vector_tags)
so_data <- adjust_data(questions_content)
last_so_data <- so_data %>% filter(last_activity_date > now()- months(3))
last_so_data_not_accepted <- last_so_data %>% filter(accepted_answer == FALSE)
last_so_data_no_activity <- last_so_data %>%
                              filter(answers == 0 & comments == 0)
```

## Row {.tabset}

### Summary 

#### Column 

##### Row {height=20%}

```{python}
#| content: valuebox
#| title: "Issues"
dict(
  icon = "inboxes",
  color = "light",
  value = len(issues)
)
```

```{python}
#| content: valuebox
#| title: "Pull Requests"
dict(
  icon = "diagram-2",
  color = "light",
  value = len(prs)
)
```

```{python}
#| content: valuebox
#| title: "Stack Overflow Questions"
dict(
  icon = "stack-overflow",
  color = "light",
  value = len(r.last_so_data)
)
```

```{python}
#| content: valuebox
#| title: "Mailing List messages"
dict(
  icon = "envelope",
  color = "light",
  value = len(data_ml)
)
```

##### Row {height=80%}

```{r}
#| title: Issues opened through the last 3 months
create_fig(py$x_issues_others, py$y_issues_others, py$y_issues_new)
```

```{r}
#| title: PRs opened through the last 3 months
create_fig(py$x_prs_others, py$y_prs_others, py$y_prs_new)
```

### Issues

#### Row

```{python}
#| content: valuebox
#| title: "Open Issues"
dict(
  icon = "list",
  color = "light",
  value = len(issues_open)
)
```

```{python}
#| content: valuebox
#| title: "Issues from New Contributors"
dict(
  icon = "egg",
  color = "success",
  value = len(issues_open_new)
)
```

```{python}
#| content: valuebox
#| title: "Issues with No Replies"
dict(
  icon = "hand-index",
  color = "warning",
  value = len(issues_open_no_replies)
)
```

#### Row 
```{r}
#| title: All open issues, new contributors highlighted
dt_show_issues(py$issues_open)
```

### PRs

#### Row

```{python}
#| content: valuebox
#| title: "Open PRs"
dict(
  icon = "diagram-2",
  color = "light",
  value = len(prs_open)
)
```

```{python}
#| content: valuebox
#| title: "PRs from New Contributors"
dict(
  icon = "emoji-heart-eyes",
  color = "success",
  value = len(prs_open_new)
)
```

```{python}
#| content: valuebox
#| title: "Unreviewed PRs"
dict(
  icon = "hand-index",
  color = "warning",
  value = len(prs_open_no_replies)
)
```

#### Row 

```{r}
#| title: All open PRs, new contributors highlighted
dt_show_issues(py$prs_open)
```

### Stack Overflow

#### Row

```{python}
#| content: valuebox
#| title: "Questions in last 90 days"
dict(
  icon = "question-square",
  color = "light",
  value = len(r.last_so_data)
)
```

```{python}
#| content: valuebox
#| title: "Questions without accepted answer"
dict(
  icon = "question-diamond",
  color = "light",
  value = len(r.last_so_data_not_accepted)
)
```

```{python}
#| content: valuebox
#| title: "Questions with no activity"
dict(
  icon = "question",
  color = "warning",
  value = len(r.last_so_data_no_activity)
)
```

#### Row 

```{r}
#| title: Stack Overflow Questions
dt_show_questions(last_so_data)
```

### Mailing List

#### Row 

```{r}
#| title: Mailing list items from the last month
dt_show_emails(py$data_ml)
```

### AI

#### Row

::: {.card}
`r py$summary_github`
:::
