---
title: "Arrow Maintainer Dashboard "
author: "updated `{r} format(Sys.time(), '%a %b %d %X %Y %Z')`"
date: last-modified
format:
  dashboard:
    theme:
      - flatly
      - custom.scss
    logo: ./images/arrow-logo.png
    nav-buttons:
      - github
      - href: https://github.com/os-maintenance/arrowdash
execute:
  error: false
---

<!--

Needs Quarto 1.4 installed to run
Seek inspiration from https://quarto.org/docs/dashboards/examples/

-->

```{r}
#| label: r_setup
#| include: false
source("./methods.R", local = knitr::knit_global())
```

# Home

{{< include overall_summary.qmd >}}

# Issues & PRs

## Row {.tabset}

### Python

```{r}
#| label: py_lang
#| include: false
lang <- "Python"
```

{{< include _data.qmd >}}

### Dummy

#### Column

##### Row

<!-- absorbs broken position 2 -->

### R

```{r}
#| label: r_lang
#| include: false
lang <- "R"
```

{{< include _data.qmd >}}

### Dummy2

#### Column

##### Row

<!-- absorbs broken position 4 -->

### C++

```{r}
#| label: cpp_lang
#| include: false
lang <- "C++"
```

{{< include _data.qmd >}}

# Project Health

{{< include maintenance_stats.qmd >}}

# Onboarding

{{< include community.qmd >}}
