name: Record Open Issue/PR Count

on:
  schedule:
    - cron: '15 0 * * *'  # Every day at 00:15 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-open-counts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R deps
        run: Rscript -e 'install.packages(c("gh", "readr", "tibble", "lubridate"))'

      - name: Run update script
        run: Rscript scripts/update_open_counts.R

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/open_counts.csv
          git diff --cached --quiet || git commit -m "Record open issue/pr counts [auto]" && git push