name: Weekly Update PR/Issue Count

on:
  schedule:
    - cron: '5 2 * 1 *' 
  workflow_dispatch:     # Allow manual runs

permissions:
  contents: write 

jobs:
  update-commit-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev pkg-config
          Rscript -e 'install.packages(c("gh", "dplyr", "lubridate", "purrr", "readr"))'

      - name: Run update script
        run: Rscript scripts/issues_prs_by_week.R

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/*
          git diff --cached --quiet || git commit -m "Update weekly count data [auto]" && git push